#!/usr/bin/env python3
"""
Mermaid Architecture & Dependency Graph Generator  v2.0
Part of the Full-Project Documenter Skill suite.

Reads the `codebase_manifest.json` generated by `codebase_analyzer.py`
and synthesizes clean, valid Mermaid diagrams:
1. High-Level System / Module Dependency Architecture (Mermaid `graph TD`)
2. Class & Interface Hierarchy (`classDiagram`) — dynamic cap per module (#10)
3. API Route Map (visual endpoint directory)
"""

import sys
import json
import argparse
from pathlib import Path
from typing import Dict, List, Any


def sanitize_id(text: str) -> str:
    """Sanitizes strings to valid Mermaid node IDs."""
    return "".join(c if c.isalnum() or c == '_' else '_' for c in text).strip('_') or "node"


def generate_module_architecture(manifest: Dict[str, Any]) -> str:
    """Generates a layered or package-level module diagram."""
    files = manifest.get("files", [])
    modules: Dict[str, Dict[str, Any]] = {}

    for f in files:
        if f.get("is_test", False):
            continue
        parts = Path(f["path"]).parts
        module_name = parts[0] if len(parts) > 1 else "root"
        if module_name not in modules:
            modules[module_name] = {"files": 0, "symbols": 0, "languages": set()}
        modules[module_name]["files"] += 1
        modules[module_name]["symbols"] += f.get("symbol_count", 0)
        modules[module_name]["languages"].add(f.get("language", "Unknown"))

    if not modules:
        return "<!-- No modules detected for architecture diagram -->"

    lines = [
        "```mermaid",
        "graph TB",
        '    subgraph SystemArchitecture ["Codebase Architectural Boundaries"]'
    ]

    for mod, data in modules.items():
        node_id = f"mod_{sanitize_id(mod)}"
        langs = ", ".join(sorted(data["languages"])[:3])
        f_count = data["files"]
        s_count = data["symbols"]
        label = f'"{mod}<br/>({f_count} files, {s_count} symbols)<br/><i>{langs}</i>"'
        lines.append(f"        {node_id}[{label}]")

    lines.append("    end")

    # Trace inter-module relationships based on imports
    dep_graph = manifest.get("dependency_graph", {})
    edges = set()
    for source_file, imports in dep_graph.items():
        src_parts = Path(source_file).parts
        src_mod = src_parts[0] if len(src_parts) > 1 else "root"
        for imp in imports:
            for target_mod in modules:
                if target_mod != src_mod and (
                    f"/{target_mod}/" in imp
                    or f"/{target_mod}" in imp
                    or imp.startswith(target_mod + "/")
                    or imp.startswith(target_mod + ".")
                    or f"from '{target_mod}" in imp
                    or f'from "{target_mod}' in imp
                ):
                    edge = (f"mod_{sanitize_id(src_mod)}", f"mod_{sanitize_id(target_mod)}")
                    edges.add(edge)

    if edges:
        lines.append("\n    %% Inferred Cross-Module Interactions")
        for src, dst in sorted(edges):
            lines.append(f"    {src} --> {dst}")

    lines.append("```\n")
    return "\n".join(lines)


def generate_class_diagram(manifest: Dict[str, Any]) -> str:
    """
    Generates Mermaid classDiagram for extracted classes & interfaces.
    FIX #10: No hardcoded cap — partitions into subdiagrams by module
    if total exceeds 40 classes.
    """
    # Collect all class-like symbols with their module
    class_entries: List[Dict[str, Any]] = []
    for f in manifest.get("files", []):
        if f.get("is_test", False):
            continue
        parts = Path(f["path"]).parts
        module = parts[0] if len(parts) > 1 else "root"
        for sym in f.get("symbols", []):
            if sym.get("type") in ("class", "interface", "struct/enum", "class_or_interface", "trait", "enum"):
                class_entries.append({**sym, "_module": module})

    if not class_entries:
        return "<!-- No explicit classes or structs detected for class diagram -->"

    # If manageable, single diagram; otherwise partition by module
    if len(class_entries) <= 40:
        return _render_class_diagram(class_entries, "All Classes & Interfaces")
    else:
        sections = []
        by_module: Dict[str, List[Dict]] = {}
        for entry in class_entries:
            mod = entry["_module"]
            by_module.setdefault(mod, []).append(entry)

        for mod, entries in sorted(by_module.items()):
            sections.append(f"### Module: `{mod}`\n")
            sections.append(_render_class_diagram(entries, mod))
        return "\n".join(sections)


def _render_class_diagram(entries: List[Dict[str, Any]], title: str) -> str:
    lines = ["```mermaid", "classDiagram"]

    for sym in entries:
        c_name = sanitize_id(sym.get("name", "Unknown"))
        sym_type = sym.get("type", "class")
        lines.append(f"    class {c_name} {{")
        if sym_type in ("interface", "trait"):
            lines.append(f"        <<{sym_type}>>")
        elif sym_type == "enum":
            lines.append("        <<enumeration>>")
        lines.append(f"        +{sym_type}")

        # Add methods if parent_class matches (Python)
        lines.append("    }")

        # Inheritance
        extends = sym.get("extends") or ""
        bases = sym.get("bases", [])
        if extends:
            parent = sanitize_id(extends.split("(")[0].split("[")[0].split("<")[0].strip())
            if parent and parent != c_name:
                lines.append(f"    {parent} <|-- {c_name}")
        elif bases:
            for base in bases[:2]:
                parent = sanitize_id(base.split("(")[0].split("[")[0].split("<")[0].strip())
                if parent and parent != c_name and parent != 'object':
                    lines.append(f"    {parent} <|-- {c_name}")

    lines.append("```\n")
    return "\n".join(lines)


def generate_route_map(manifest: Dict[str, Any]) -> str:
    """Generates a visual route map from extracted endpoints."""
    routes = manifest.get("routes", [])
    if not routes:
        return "<!-- No API routes detected -->"

    lines = ["```mermaid", 'graph LR']
    lines.append('    subgraph APIRoutes ["Detected API Endpoints"]')

    seen = set()
    for i, route in enumerate(routes):
        method = route.get("method", "ANY")
        path = route.get("path", "/")
        key = f"{method}_{path}"
        if key in seen:
            continue
        seen.add(key)
        node_id = f"route_{sanitize_id(key)}_{i}"
        label = f'"{method} {path}"'
        lines.append(f"        {node_id}[{label}]")

    lines.append("    end")
    lines.append("```\n")
    return "\n".join(lines)


def main():
    parser = argparse.ArgumentParser(description="Generate Mermaid diagrams from codebase manifest v2.0")
    parser.add_argument("manifest", nargs="?", default="codebase_manifest.json", help="Path to codebase_manifest.json")
    parser.add_argument("--output", "-o", default="ARCHITECTURE_DIAGRAMS.md", help="Output markdown file")
    args = parser.parse_args()

    manifest_path = Path(args.manifest)
    if not manifest_path.exists():
        print(f"Error: Manifest file {manifest_path} not found. Run codebase_analyzer.py first.", file=sys.stderr)
        sys.exit(1)

    manifest = json.loads(manifest_path.read_text(encoding='utf-8'))
    total_files = len(manifest.get('files', []))
    total_routes = len(manifest.get('routes', []))
    print(f"[*] Processing {total_files} files ({total_routes} routes) for Mermaid diagrams...")

    module_diag = generate_module_architecture(manifest)
    class_diag = generate_class_diagram(manifest)
    route_diag = generate_route_map(manifest)

    out_content = f"""# System Architecture & Dependency Graphs

Generated automatically from project manifest.

## 1. High-Level Architectural Boundaries & Module Topology

{module_diag}

## 2. Core Domain Model & Class Structures

{class_diag}

## 3. API Route Map

{route_diag}
"""

    out_file = Path(args.output)
    out_file.write_text(out_content, encoding='utf-8')
    print(f"[+] Mermaid architecture document generated at: {out_file.resolve()}")


if __name__ == "__main__":
    main()
